// src/pages/provider/ProviderDashboard.jsx
import React, { useState, useEffect } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import DashboardLayout from '../../components/layout/DashboardLayout'
import { ToastProvider } from '../../components/common/Toast'
import Spinner from '../../components/common/Spinner'
import { useAuth } from '../../context/AuthContext'
import { getMyProviderProfile } from '../../api/providerService'
import { countAvailableSlots } from '../../api/scheduleService'
import {
  Clock, CheckCircle, XCircle, AlertCircle, ArrowRight,
  CalendarPlus, Settings, BarChart3, ShieldCheck
} from 'lucide-react'

function StatusBanner({ status, reason }) {
  if (status === 'APPROVED') return (
    <div className="rounded-xl bg-emerald-50 border border-emerald-200 p-4 flex items-start gap-3">
      <CheckCircle className="h-5 w-5 text-emerald-500 flex-shrink-0 mt-0.5" />
      <div>
        <p className="text-sm font-semibold text-emerald-800">Profile Approved</p>
        <p className="text-xs text-emerald-600 mt-0.5">You can now add slots and accept appointments.</p>
      </div>
    </div>
  )
  if (status === 'PENDING') return (
    <div className="rounded-xl bg-amber-50 border border-amber-200 p-4 flex items-start gap-3">
      <AlertCircle className="h-5 w-5 text-amber-500 flex-shrink-0 mt-0.5" />
      <div>
        <p className="text-sm font-semibold text-amber-800">Awaiting Admin Approval</p>
        <p className="text-xs text-amber-600 mt-0.5">Your profile has been submitted and is under review. You'll be notified once approved.</p>
      </div>
    </div>
  )
  if (status === 'REJECTED') return (
    <div className="rounded-xl bg-red-50 border border-red-200 p-4 flex items-start gap-3">
      <XCircle className="h-5 w-5 text-red-500 flex-shrink-0 mt-0.5" />
      <div>
        <p className="text-sm font-semibold text-red-800">Profile Rejected</p>
        {reason && <p className="text-xs text-red-600 mt-0.5"><strong>Reason:</strong> {reason}</p>}
        <p className="text-xs text-red-600 mt-1">Please update your profile and contact support for re-review.</p>
      </div>
    </div>
  )
  return null
}

function ProviderDashboardInner() {
  const { user } = useAuth()
  const navigate = useNavigate()
  const [profile, setProfile]     = useState(null)
  const [slotCount, setSlotCount] = useState(null)
  const [loading, setLoading]     = useState(true)
  const [noProfile, setNoProfile] = useState(false)

  useEffect(() => {
    if (!user?.userId) return
    getMyProviderProfile(user.userId)
      .then(async res => {
        const p = res.data
        setProfile(p)
        if (p.verificationStatus === 'APPROVED') {
          try {
            const sc = await countAvailableSlots(p.providerId)
            setSlotCount(sc.data.availableSlots)
          } catch {}
        }
      })
      .catch(err => {
        if (err.response?.status === 404) setNoProfile(true)
      })
      .finally(() => setLoading(false))
  }, [user])

  const hour = new Date().getHours()
  const greeting = hour < 12 ? 'Good morning' : hour < 17 ? 'Good afternoon' : 'Good evening'

  if (loading) return <DashboardLayout><div className="flex justify-center py-20"><Spinner size="lg" /></div></DashboardLayout>

  return (
    <DashboardLayout>
      <div className="animate-fade-in space-y-6">
        <div className="page-header">
          <h1 className="page-title">{greeting}, {user?.fullName?.split(' ')[0] || 'Doctor'}.</h1>
          <p className="page-subtitle">Manage your practice and availability</p>
        </div>

        {/* No profile yet */}
        {noProfile && (
          <div className="card border-navy-200 bg-navy-50">
            <div className="flex items-start gap-4">
              <div className="h-10 w-10 rounded-xl bg-navy-700 flex items-center justify-center flex-shrink-0">
                <ShieldCheck className="h-5 w-5 text-white" />
              </div>
              <div className="flex-1">
                <h3 className="font-serif text-base text-navy-900 mb-1">Complete your doctor profile</h3>
                <p className="text-sm text-slate-500 mb-4">Set up your profile to get verified and start accepting patients.</p>
                <Link to="/provider/setup" className="btn-primary text-sm inline-flex items-center gap-2">
                  Set Up Profile <ArrowRight className="h-4 w-4" />
                </Link>
              </div>
            </div>
          </div>
        )}

        {/* Status banner */}
        {profile && <StatusBanner status={profile.verificationStatus} reason={profile.rejectionReason} />}

        {/* Stats — only show when approved */}
        {profile?.verificationStatus === 'APPROVED' && (
          <div className="grid sm:grid-cols-3 gap-4">
            <div className="card">
              <p className="section-label">Available Slots</p>
              <p className="font-serif text-3xl text-navy-900">{slotCount ?? '—'}</p>
              <p className="text-xs text-slate-400 mt-1">open for booking</p>
            </div>
            <div className="card">
              <p className="section-label">Availability</p>
              <div className="flex items-center gap-2 mt-1">
                <span className={`h-2.5 w-2.5 rounded-full ${profile.isAvailable ? 'bg-emerald-500' : 'bg-slate-300'}`} />
                <span className="font-serif text-lg text-navy-900">
                  {profile.isAvailable ? 'Accepting Patients' : 'On Leave'}
                </span>
              </div>
            </div>
            <div className="card">
              <p className="section-label">Rating</p>
              <p className="font-serif text-3xl text-navy-900">
                {profile.avgRating > 0 ? profile.avgRating.toFixed(1) : 'New'}
              </p>
              <p className="text-xs text-slate-400 mt-1">average rating</p>
            </div>
          </div>
        )}

        {/* Quick actions */}
        {profile?.verificationStatus === 'APPROVED' && (
          <div className="card">
            <h2 className="font-serif text-lg text-navy-900 mb-4">Quick Actions</h2>
            <div className="grid sm:grid-cols-3 gap-3">
              {[
                { label: 'Add Slots',       icon: CalendarPlus, to: '/provider/slots',   desc: 'Create new availability' },
                { label: 'Edit Profile',    icon: Settings,     to: '/provider/profile',  desc: 'Update your details' },
              ].map(a => (
                <Link key={a.label} to={a.to}
                  className="flex items-start gap-3 p-4 rounded-xl border border-slate-200 hover:border-navy-300 hover:bg-navy-50 transition-all duration-200">
                  <div className="h-9 w-9 rounded-lg bg-navy-700 flex items-center justify-center flex-shrink-0">
                    <a.icon className="h-4.5 w-4.5 text-white" />
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-slate-800">{a.label}</p>
                    <p className="text-xs text-slate-400">{a.desc}</p>
                  </div>
                </Link>
              ))}
            </div>
          </div>
        )}

        {/* Profile summary if exists */}
        {profile && (
          <div className="card">
            <div className="flex items-center justify-between mb-4">
              <h2 className="font-serif text-lg text-navy-900">My Profile</h2>
              <Link to="/provider/profile" className="text-sm text-navy-600 hover:underline">Edit</Link>
            </div>
            <div className="grid sm:grid-cols-2 gap-3 text-sm">
              {[
                ['Specialization', profile.specialization],
                ['Qualification',  profile.qualification],
                ['Experience',     `${profile.experienceYears} years`],
                ['Clinic',         profile.clinicName || '—'],
                ['Location',       profile.clinicAddress || '—'],
                ['Fee',            profile.consultationFee > 0 ? `₹${profile.consultationFee}` : 'Not set'],
              ].map(([k, v]) => (
                <div key={k}>
                  <p className="text-xs text-slate-400 font-medium">{k}</p>
                  <p className="text-slate-700 mt-0.5">{v}</p>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </DashboardLayout>
  )
}

export default function ProviderDashboard() {
  return <ToastProvider><ProviderDashboardInner /></ToastProvider>
}

// src/app/features/provider/provider-dashboard.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { SidebarLayoutComponent, NavItem } from '../../shared/components/sidebar-layout.component';
import { AuthService } from '../../core/services/auth.service';
import { ProviderService } from '../../core/services/provider.service';
import { AppointmentService } from '../../core/services/appointment.service';
import { ProviderResponse, AppointmentSummary, AppointmentCount } from '../../core/models';
import { StatusBadgePipe, FormatTimePipe, FormatDatePipe } from '../../shared/pipes/status.pipe';
import { IconComponent } from '../../shared/components/icon.component';

@Component({
  selector: 'app-provider-dashboard',
  standalone: true,
  imports: [CommonModule, RouterModule, SidebarLayoutComponent, StatusBadgePipe, FormatTimePipe, FormatDatePipe, IconComponent],
  template: `
    <app-sidebar-layout [navItems]="navItems">
      <div class="page-enter">
        <div class="mb-8">
          <h1 class="text-3xl font-serif text-navy-700">Provider Dashboard</h1>
          <p class="text-gray-500 mt-1">Manage your practice</p>
        </div>

        <!-- Verification Status Banner -->
        @if (profile) {
          @if (profile.verificationStatus === 'PENDING') {
            <div class="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-6 flex items-start gap-3">
              <app-icon name="clock" sizeClass="w-6 h-6 text-amber-500 flex-shrink-0 mt-0.5"></app-icon>
              <div>
                <p class="font-semibold text-amber-800">Verification Pending</p>
                <p class="text-amber-700 text-sm">Your profile is under review. You'll be notified once approved.</p>
              </div>
            </div>
          }
          @if (profile.verificationStatus === 'APPROVED') {
            <div class="bg-emerald-50 border border-emerald-200 rounded-xl p-4 mb-6 flex items-start gap-3">
              <app-icon name="check-circle" sizeClass="w-6 h-6 text-emerald-500 flex-shrink-0 mt-0.5"></app-icon>
              <div>
                <p class="font-semibold text-emerald-800">Verified Provider</p>
                <p class="text-emerald-700 text-sm">Your profile is active. Patients can book appointments with you.</p>
              </div>
            </div>
          }
          @if (profile.verificationStatus === 'REJECTED') {
            <div class="bg-red-50 border border-red-200 rounded-xl p-4 mb-6 flex items-start gap-3">
              <app-icon name="x-circle" sizeClass="w-6 h-6 text-red-500 flex-shrink-0 mt-0.5"></app-icon>
              <div>
                <p class="font-semibold text-red-800">Verification Rejected</p>
                @if (profile.rejectionReason) {
                  <p class="text-red-700 text-sm">Reason: {{ profile.rejectionReason }}</p>
                }
                <p class="text-red-600 text-sm mt-1">Please update your profile and contact support.</p>
              </div>
            </div>
          }
        }

        <!-- No profile yet -->
        @if (!profileLoading && !profile) {
          <div class="card text-center py-12 mb-6">
            <div class="inline-block p-4 bg-navy-50 rounded-xl mb-4">
              <app-icon name="user" sizeClass="w-10 h-10 text-navy-700"></app-icon>
            </div>
            <h2 class="text-xl font-serif text-navy-700 mb-2">Complete Your Profile</h2>
            <p class="text-gray-500 mb-6">Set up your provider profile to start accepting appointments.</p>
            <a routerLink="/provider/profile-setup" class="btn-primary">Set Up Profile</a>
          </div>
        }

        <!-- Profile Card -->
        @if (profile && !profileLoading) {
          <div class="card mb-8 flex flex-col sm:flex-row items-start sm:items-center gap-6">
            <div class="w-24 h-24 rounded-2xl bg-navy-100 flex-shrink-0 flex items-center justify-center overflow-hidden">
              @if (profile.profilePicUrl) {
                <img [src]="profile.profilePicUrl" class="w-full h-full object-cover" alt="{{ profile.specialization }}">
              } @else {
                <app-icon name="user" sizeClass="w-12 h-12 text-navy-400"></app-icon>
              }
            </div>
            <div class="flex-1">
              <h2 class="text-2xl font-serif text-navy-700 mb-1">Dr. {{ (auth.currentUser()?.fullName || 'Provider') }}</h2>
              <p class="text-lg text-navy-600 font-medium mb-2">{{ profile.specialization }}</p>
              <p class="text-gray-600 text-sm">{{ profile.qualification }} • {{ profile.experienceYears }} years experience</p>
              @if (profile.clinicName) {
                <p class="text-gray-500 text-sm mt-2 flex items-center gap-2">
                  <app-icon name="hospital" sizeClass="w-4 h-4"></app-icon>
                  {{ profile.clinicName }}
                </p>
              }
            </div>
            <a routerLink="/provider/profile" class="btn-secondary text-sm flex-shrink-0">Edit Profile</a>
          </div>
        }

        <!-- Stats -->
        <div class="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
          <div class="card">
            <div class="mb-2"><app-icon name="calendar" sizeClass="w-6 h-6 text-navy-700"></app-icon></div>
            <p class="text-2xl font-bold text-navy-700">{{ counts?.scheduled || 0 }}</p>
            <p class="text-gray-500 text-xs mt-0.5">Scheduled</p>
          </div>
          <div class="card">
            <div class="mb-2"><app-icon name="check-circle" sizeClass="w-6 h-6 text-emerald-600"></app-icon></div>
            <p class="text-2xl font-bold text-navy-700">{{ counts?.completed || 0 }}</p>
            <p class="text-gray-500 text-xs mt-0.5">Completed</p>
          </div>
          <div class="card">
            <div class="mb-2"><app-icon name="x-circle" sizeClass="w-6 h-6 text-red-600"></app-icon></div>
            <p class="text-2xl font-bold text-navy-700">{{ counts?.cancelled || 0 }}</p>
            <p class="text-gray-500 text-xs mt-0.5">Cancelled</p>
          </div>
          <div class="card">
            <div class="mb-2"><app-icon name="info" sizeClass="w-6 h-6 text-blue-600"></app-icon></div>
            <p class="text-2xl font-bold text-navy-700">{{ counts?.total || 0 }}</p>
            <p class="text-gray-500 text-xs mt-0.5">Total</p>
          </div>
        </div>

        <!-- Today's schedule -->
        <div class="card">
          <div class="flex items-center justify-between mb-5">
            <h2 class="text-xl font-serif text-navy-700">Today's Schedule</h2>
            <a routerLink="/provider/appointments" class="text-sm text-emerald-600 hover:underline">View all</a>
          </div>
          @if (todayLoading) {
            <div class="space-y-3">
              @for (i of [1,2]; track i) {
                <div class="h-16 bg-gray-100 rounded-xl animate-pulse"></div>
              }
            </div>
          }
          @if (!todayLoading && today.length === 0) {
            <div class="text-center py-8 text-gray-400">
              <p>No appointments today.</p>
            </div>
          }
          @if (!todayLoading) {
            <div class="divide-y divide-gray-100">
              @for (appt of today; track appt.appointmentId) {
                <div class="py-4 flex items-center justify-between">
                  <div>
                    <p class="font-medium text-gray-900">{{ appt.serviceType }}</p>
                    <p class="text-sm text-gray-500">{{ appt.startTime | formatTime }} – {{ appt.endTime | formatTime }}</p>
                  </div>
                  <span [ngClass]="appt.status | statusBadge">{{ appt.status }}</span>
                </div>
              }
            </div>
          }
        </div>
      </div>
    </app-sidebar-layout>
  `
})
export class ProviderDashboardComponent implements OnInit {
  auth = inject(AuthService);
  private providerService = inject(ProviderService);
  private apptService = inject(AppointmentService);

  navItems: NavItem[] = [
    { label: 'Dashboard', iconName: 'info', route: '/provider/dashboard' },
    { label: 'Appointments', iconName: 'calendar', route: '/provider/appointments' },
    { label: 'Slot Management', iconName: 'calendar', route: '/provider/slots' },
    { label: 'My Profile', iconName: 'user', route: '/provider/profile' },
  ];

  profile: ProviderResponse | null = null;
  profileLoading = true;
  today: AppointmentSummary[] = [];
  todayLoading = true;
  counts: AppointmentCount | null = null;

  ngOnInit(): void {
    const userId = this.auth.currentUser()!.userId;
    this.providerService.getMyProfile(userId).subscribe({
      next: (p) => {
        this.profile = p;
        this.profileLoading = false;
        this.loadAppointments(p.providerId);
      },
      error: () => { this.profileLoading = false; this.todayLoading = false; }
    });
  }

  loadAppointments(providerId: string): void {
    this.apptService.getProviderToday(providerId).subscribe({
      next: (a) => { this.today = a; this.todayLoading = false; },
      error: () => { this.todayLoading = false; }
    });
    this.apptService.getProviderCount(providerId).subscribe({
      next: (c) => this.counts = c
    });
  }
}
