// src/pages/admin/AdminProviderDetail.jsx
import React, { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import DashboardLayout from '../../components/layout/DashboardLayout'
import { ToastProvider, useToast } from '../../components/common/Toast'
import Spinner from '../../components/common/Spinner'
import { ErrorMessage } from '../../components/common/Feedback'
import ConfirmModal from '../../components/common/ConfirmModal'
import { getProviderById, verifyProvider, rejectProvider, unverifyProvider, deleteProvider } from '../../api/providerService'
import {
  ArrowLeft, CheckCircle, XCircle, Clock, Star, MapPin,
  GraduationCap, Stethoscope, IndianRupee, RefreshCw, Trash2, X
} from 'lucide-react'

function RejectModal({ open, onConfirm, onClose, loading }) {
  const [reason, setReason] = useState('')
  useEffect(() => { if (!open) setReason('') }, [open])
  if (!open) return null
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-navy-950/40 backdrop-blur-sm" onClick={onClose} />
      <div className="relative bg-white rounded-2xl shadow-card-hover max-w-md w-full p-6 animate-slide-up">
        <div className="flex items-center justify-between mb-4">
          <h3 className="font-serif text-lg text-slate-900">Reject Provider</h3>
          <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-slate-100"><X className="h-4 w-4" /></button>
        </div>
        <p className="text-sm text-slate-500 mb-4">Provide a clear reason so the provider can address the issue.</p>
        <textarea rows={4} className="input-field resize-none mb-4" placeholder="e.g. Registration number not provided. Please resubmit with valid medical council ID."
          value={reason} onChange={e => setReason(e.target.value)} />
        <div className="flex gap-3 justify-end">
          <button onClick={onClose} className="btn-secondary" disabled={loading}>Cancel</button>
          <button onClick={() => reason.trim() && onConfirm(reason.trim())}
            disabled={!reason.trim() || loading} className="btn-danger">
            {loading ? 'Rejecting…' : 'Reject'}
          </button>
        </div>
      </div>
    </div>
  )
}

function AdminProviderDetailInner() {
  const { id }   = useParams()
  const navigate = useNavigate()
  const toast    = useToast()

  const [provider, setProvider]       = useState(null)
  const [loading, setLoading]         = useState(true)
  const [error, setError]             = useState(null)
  const [actionLoading, setActionLoading] = useState(false)
  const [showReject, setShowReject]   = useState(false)
  const [showDelete, setShowDelete]   = useState(false)
  const [deleting, setDeleting]       = useState(false)

  const load = () => {
    setLoading(true)
    getProviderById(id)
      .then(res => setProvider(res.data))
      .catch(err => setError(err.response?.data?.error || 'Provider not found.'))
      .finally(() => setLoading(false))
  }

  useEffect(() => { load() }, [id])

  const handleApprove = async () => {
    setActionLoading(true)
    try {
      await verifyProvider(id)
      toast.success('Provider approved.')
      setProvider(p => ({...p, verificationStatus: 'APPROVED', isVerified: true, rejectionReason: null}))
    } catch (err) { toast.error(err.response?.data?.error || 'Approval failed.') }
    finally { setActionLoading(false) }
  }

  const handleReject = async (reason) => {
    setActionLoading(true)
    try {
      await rejectProvider(id, reason)
      toast.success('Provider rejected.')
      setProvider(p => ({...p, verificationStatus: 'REJECTED', isVerified: false, rejectionReason: reason}))
      setShowReject(false)
    } catch (err) { toast.error(err.response?.data?.error || 'Rejection failed.') }
    finally { setActionLoading(false) }
  }

  const handleReset = async () => {
    setActionLoading(true)
    try {
      await unverifyProvider(id)
      toast.success('Provider reset to Pending.')
      setProvider(p => ({...p, verificationStatus: 'PENDING', isVerified: false}))
    } catch (err) { toast.error(err.response?.data?.error || 'Reset failed.') }
    finally { setActionLoading(false) }
  }

  const handleDelete = async () => {
    setDeleting(true)
    try {
      await deleteProvider(id)
      toast.success('Provider deleted.')
      navigate('/admin/providers', { replace: true })
    } catch (err) { toast.error(err.response?.data?.error || 'Delete failed.') }
    finally { setDeleting(false) }
  }

  if (loading) return <DashboardLayout><div className="flex justify-center py-20"><Spinner size="lg" /></div></DashboardLayout>
  if (error)   return <DashboardLayout><div className="max-w-md"><ErrorMessage message={error} /></div></DashboardLayout>

  const status = provider.verificationStatus
  const StatusBadge = () => {
    if (status === 'APPROVED') return <span className="badge-approved text-sm px-3 py-1.5"><CheckCircle className="h-4 w-4" />Approved</span>
    if (status === 'REJECTED') return <span className="badge-rejected text-sm px-3 py-1.5"><XCircle className="h-4 w-4" />Rejected</span>
    return <span className="badge-pending text-sm px-3 py-1.5"><Clock className="h-4 w-4" />Pending Review</span>
  }

  return (
    <DashboardLayout>
      <div className="animate-fade-in max-w-3xl">
        <button onClick={() => navigate(-1)} className="flex items-center gap-2 text-sm text-slate-500 hover:text-navy-700 mb-6 transition-colors">
          <ArrowLeft className="h-4 w-4" /> Back
        </button>

        {/* Header card */}
        <div className="card mb-5">
          <div className="flex items-start justify-between gap-4 flex-wrap">
            <div className="flex items-start gap-4">
              <div className="h-16 w-16 rounded-2xl bg-gradient-to-br from-navy-700 to-navy-500 flex items-center justify-center text-white font-serif text-xl overflow-hidden flex-shrink-0">
                {provider.profilePicUrl ? <img src={provider.profilePicUrl} alt="" className="h-full w-full object-cover" /> : provider.clinicName?.slice(0,2) || 'DR'}
              </div>
              <div>
                <h1 className="font-serif text-2xl text-navy-900">{provider.clinicName || 'Medical Clinic'}</h1>
                <p className="text-emerald-600 font-medium">{provider.specialization}</p>
                <p className="text-sm text-slate-500 mt-0.5">Provider ID: #{provider.providerId} · User ID: #{provider.userId}</p>
              </div>
            </div>
            <StatusBadge />
          </div>

          {/* Rejection reason */}
          {status === 'REJECTED' && provider.rejectionReason && (
            <div className="mt-4 rounded-xl bg-red-50 border border-red-200 p-3">
              <p className="text-xs font-semibold text-red-700 mb-1">Rejection Reason:</p>
              <p className="text-sm text-red-600">{provider.rejectionReason}</p>
            </div>
          )}
        </div>

        <div className="grid sm:grid-cols-2 gap-5 mb-5">
          {/* Professional details */}
          <div className="card">
            <h2 className="font-serif text-base text-navy-900 mb-4">Professional Details</h2>
            <div className="space-y-3">
              {[
                { icon: GraduationCap, label: 'Qualification',  val: provider.qualification },
                { icon: Stethoscope,   label: 'Specialization', val: provider.specialization },
                { icon: Clock,         label: 'Experience',     val: `${provider.experienceYears} years` },
                { icon: Star,          label: 'Rating',         val: provider.avgRating > 0 ? provider.avgRating.toFixed(1) : 'Not rated' },
                { icon: IndianRupee,   label: 'Consultation Fee', val: provider.consultationFee > 0 ? `₹${provider.consultationFee}` : 'Not set' },
              ].map(item => (
                <div key={item.label} className="flex items-start gap-3">
                  <item.icon className="h-4 w-4 text-navy-400 mt-0.5 flex-shrink-0" />
                  <div>
                    <p className="text-xs text-slate-400">{item.label}</p>
                    <p className="text-sm text-slate-700">{item.val}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Clinic details */}
          <div className="card">
            <h2 className="font-serif text-base text-navy-900 mb-4">Clinic Information</h2>
            <div className="space-y-3">
              {provider.clinicAddress && (
                <div className="flex items-start gap-3">
                  <MapPin className="h-4 w-4 text-navy-400 mt-0.5 flex-shrink-0" />
                  <div>
                    <p className="text-xs text-slate-400">Address</p>
                    <p className="text-sm text-slate-700">{provider.clinicAddress}</p>
                  </div>
                </div>
              )}
              <div>
                <p className="text-xs text-slate-400 mb-1">Availability</p>
                <span className={`text-sm font-medium ${provider.isAvailable ? 'text-emerald-600' : 'text-slate-400'}`}>
                  {provider.isAvailable ? 'Currently accepting patients' : 'On leave'}
                </span>
              </div>
              {provider.bio && (
                <div>
                  <p className="text-xs text-slate-400 mb-1">Bio</p>
                  <p className="text-sm text-slate-600 leading-relaxed">{provider.bio}</p>
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Action buttons */}
        <div className="card">
          <h2 className="font-serif text-base text-navy-900 mb-4">Admin Actions</h2>
          <div className="flex flex-wrap gap-3">
            {status !== 'APPROVED' && (
              <button onClick={handleApprove} disabled={actionLoading}
                className="btn-success flex items-center gap-2 text-sm">
                <CheckCircle className="h-4 w-4" />
                {actionLoading ? 'Approving…' : 'Approve Provider'}
              </button>
            )}
            {status !== 'REJECTED' && (
              <button onClick={() => setShowReject(true)} disabled={actionLoading}
                className="btn-danger flex items-center gap-2 text-sm">
                <XCircle className="h-4 w-4" />
                Reject Provider
              </button>
            )}
            {status !== 'PENDING' && (
              <button onClick={handleReset} disabled={actionLoading}
                className="btn-secondary flex items-center gap-2 text-sm">
                <RefreshCw className="h-4 w-4" />
                {actionLoading ? 'Resetting…' : 'Reset to Pending'}
              </button>
            )}
            <button onClick={() => setShowDelete(true)}
              className="ml-auto flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium text-red-600 hover:bg-red-50 border border-red-200 transition-colors">
              <Trash2 className="h-4 w-4" /> Delete Provider
            </button>
          </div>
        </div>
      </div>

      <RejectModal
        open={showReject}
        onConfirm={handleReject}
        onClose={() => setShowReject(false)}
        loading={actionLoading}
      />
      <ConfirmModal
        isOpen={showDelete}
        title="Delete provider?"
        message="This action is irreversible. All provider data will be permanently removed."
        onConfirm={handleDelete}
        onCancel={() => setShowDelete(false)}
        confirmLabel="Delete Permanently"
        loading={deleting}
      />
    </DashboardLayout>
  )
}

export default function AdminProviderDetail() {
  return <ToastProvider><AdminProviderDetailInner /></ToastProvider>
}

// src/app/features/admin/admin-provider-detail.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule, ActivatedRoute, Router } from '@angular/router';
import { SidebarLayoutComponent, NavItem } from '../../shared/components/sidebar-layout.component';
import { ConfirmModalComponent } from '../../shared/components/confirm-modal.component';
import { ProviderService } from '../../core/services/provider.service';
import { ToastService } from '../../core/services/toast.service';
import { ProviderResponse } from '../../core/models';
import { StatusBadgePipe, FormatDatePipe } from '../../shared/pipes/status.pipe';

@Component({
  selector: 'app-admin-provider-detail',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule, SidebarLayoutComponent, ConfirmModalComponent, StatusBadgePipe, FormatDatePipe],
  template: `
    <app-sidebar-layout [navItems]="navItems">
      <div class="page-enter">
        <div class="mb-6">
          <a routerLink="/admin/providers" class="text-sm text-gray-500 hover:text-gray-700 flex items-center gap-1 mb-4">
            ← Back to Providers
          </a>
          <h1 class="text-3xl font-serif text-navy-700">Provider Detail</h1>
        </div>

        @if (loading) {
          <div class="card animate-pulse h-64"></div>
        }

        @if (!loading && provider) {
          <!-- Status banner -->
          <div class="rounded-xl p-4 mb-6 flex items-start justify-between gap-4"
            [ngClass]="{
              'bg-amber-50 border border-amber-200': provider.verificationStatus === 'PENDING',
              'bg-emerald-50 border border-emerald-200': provider.verificationStatus === 'APPROVED',
              'bg-red-50 border border-red-200': provider.verificationStatus === 'REJECTED'
            }">
            <div class="flex items-start gap-3">
              <span class="text-2xl">
                {{ provider.verificationStatus === 'PENDING' ? '⏳' : provider.verificationStatus === 'APPROVED' ? '✅' : '❌' }}
              </span>
              <div>
                <span [ngClass]="provider.verificationStatus | statusBadge" class="mb-1">{{ provider.verificationStatus }}</span>
                @if (provider.verificationStatus === 'REJECTED' && provider.rejectionReason) {
                  <p class="text-red-700 text-sm mt-1">Reason: {{ provider.rejectionReason }}</p>
                }
              </div>
            </div>
            <!-- Actions -->
            <div class="flex gap-2 flex-wrap justify-end">
              @if (provider.verificationStatus === 'PENDING' || provider.verificationStatus === 'REJECTED') {
                <button (click)="approve()" [disabled]="acting" class="btn-emerald text-sm py-2">Approve</button>
              }
              @if (provider.verificationStatus === 'PENDING' || provider.verificationStatus === 'APPROVED') {
                <button (click)="openRejectModal()" class="btn-danger text-sm py-2">Reject</button>
              }
              @if (provider.verificationStatus === 'APPROVED') {
                <button (click)="resetToP()" [disabled]="acting" class="btn-secondary text-sm py-2">Reset to Pending</button>
              }
              <button (click)="openDeleteModal()" class="btn-danger text-sm py-2">Delete</button>
            </div>
          </div>

          <!-- Details card -->
          <div class="card mb-6">
            <div class="flex items-start gap-5 mb-6">
              <div class="w-20 h-20 bg-navy-100 rounded-2xl flex items-center justify-center text-navy-700 font-bold text-3xl overflow-hidden flex-shrink-0">
                @if (provider.profilePicUrl) {
                  <img [src]="provider.profilePicUrl" class="w-full h-full object-cover" alt="">
                } @else {
                  {{ provider.specialization[0] }}
                }
              </div>
              <div>
                <h2 class="text-xl font-serif text-navy-700 mb-1">{{ provider.specialization }}</h2>
                <p class="text-gray-600">{{ provider.qualification }}</p>
                <p class="text-gray-400 text-sm">{{ provider.experienceYears }} years experience</p>
                @if (provider.consultationFee) {
                  <p class="text-navy-700 font-semibold mt-1">₹{{ provider.consultationFee }} consultation fee</p>
                }
              </div>
            </div>

            <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm mb-4">
              @if (provider.clinicName) {
                <div>
                  <span class="text-gray-400">Clinic</span>
                  <p class="text-gray-900 font-medium">{{ provider.clinicName }}</p>
                </div>
              }
              @if (provider.clinicAddress) {
                <div>
                  <span class="text-gray-400">Address</span>
                  <p class="text-gray-900 font-medium">{{ provider.clinicAddress }}</p>
                </div>
              }
              @if (provider.avgRating) {
                <div>
                  <span class="text-gray-400">Rating</span>
                  <p class="text-gray-900 font-medium">★ {{ provider.avgRating.toFixed(1) }}</p>
                </div>
              }
              <div>
                <span class="text-gray-400">Registered</span>
                <p class="text-gray-900 font-medium">{{ provider.createdAt | formatDate }}</p>
              </div>
              <div>
                <span class="text-gray-400">Availability</span>
                <p class="font-medium" [ngClass]="provider.available ? 'text-emerald-600' : 'text-red-500'">
                  {{ provider.available ? 'Available' : 'Not Available' }}
                </p>
              </div>
            </div>

            @if (provider.bio) {
              <div class="border-t border-gray-100 pt-4">
                <p class="text-gray-400 text-xs mb-1">Bio</p>
                <p class="text-gray-700 text-sm leading-relaxed">{{ provider.bio }}</p>
              </div>
            }
          </div>
        }
      </div>
    </app-sidebar-layout>

    <!-- Reject Modal -->
    <app-confirm-modal
      [open]="rejectModal"
      title="Reject Provider"
      message="Provide a reason for rejection. The provider will see this message."
      confirmText="Reject"
      cancelText="Cancel"
      [danger]="true"
      [requireReason]="true"
      reasonLabel="Rejection Reason"
      (confirmed)="confirmReject($event)"
      (cancelled)="rejectModal = false">
    </app-confirm-modal>

    <!-- Delete Modal -->
    <app-confirm-modal
      [open]="deleteModal"
      title="Delete Provider"
      message="This will permanently remove the provider. This action cannot be undone."
      confirmText="Delete"
      cancelText="Cancel"
      [danger]="true"
      (confirmed)="confirmDelete()"
      (cancelled)="deleteModal = false">
    </app-confirm-modal>
  `
})
export class AdminProviderDetailComponent implements OnInit {
  private route = inject(ActivatedRoute);
  private router = inject(Router);
  private providerService = inject(ProviderService);
  private toast = inject(ToastService);

  navItems: NavItem[] = [
    { label: 'Dashboard', iconName: 'info', route: '/admin/dashboard' },
    { label: 'Pending Approvals', iconName: 'clock', route: '/admin/pending' },
    { label: 'All Providers', iconName: 'user', route: '/admin/providers' },
  ];

  provider: ProviderResponse | null = null;
  loading = true;
  acting = false;
  rejectModal = false;
  deleteModal = false;

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id')!;
    this.providerService.getById(id).subscribe({
      next: (p) => { this.provider = p; this.loading = false; },
      error: () => { this.loading = false; }
    });
  }

  approve(): void {
    this.acting = true;
    this.providerService.approve(this.provider!.providerId).subscribe({
      next: () => {
        this.acting = false;
        this.provider = { ...this.provider!, verificationStatus: 'APPROVED', verified: true };
        this.toast.success('Provider approved!');
      },
      error: () => { this.acting = false; this.toast.error('Failed.'); }
    });
  }

  openRejectModal(): void { this.rejectModal = true; }

  confirmReject(reason: string): void {
    this.rejectModal = false;
    this.providerService.reject(this.provider!.providerId, reason).subscribe({
      next: () => {
        this.provider = { ...this.provider!, verificationStatus: 'REJECTED', verified: false, rejectionReason: reason };
        this.toast.info('Provider rejected.');
      },
      error: () => this.toast.error('Failed.')
    });
  }

  resetToP(): void {
    this.acting = true;
    this.providerService.unverify(this.provider!.providerId).subscribe({
      next: (p) => { this.acting = false; this.provider = p; this.toast.info('Reset to pending.'); },
      error: () => { this.acting = false; this.toast.error('Failed.'); }
    });
  }

  openDeleteModal(): void { this.deleteModal = true; }

  confirmDelete(): void {
    this.deleteModal = false;
    this.providerService.delete(this.provider!.providerId).subscribe({
      next: () => { this.toast.success('Provider deleted.'); this.router.navigate(['/admin/providers']); },
      error: () => this.toast.error('Delete failed.')
    });
  }
}
