// src/pages/patient/PatientDashboard.jsx
import React, { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import DashboardLayout from '../../components/layout/DashboardLayout'
import { ToastProvider } from '../../components/common/Toast'
import { useAuth } from '../../context/AuthContext'
import { getVerifiedProviders } from '../../api/providerService'
import { Search, Calendar, Clock, ArrowRight, User } from 'lucide-react'

function PatientDashboardInner() {
  const { user } = useAuth()
  const [topProviders, setTopProviders] = useState([])

  useEffect(() => {
    getVerifiedProviders()
      .then(res => setTopProviders(res.data.slice(0, 3)))
      .catch(() => {})
  }, [])

  const hour = new Date().getHours()
  const greeting = hour < 12 ? 'Good morning' : hour < 17 ? 'Good afternoon' : 'Good evening'
  const firstName = user?.fullName?.split(' ')[0] || 'there'

  return (
    <DashboardLayout>
      <div className="animate-fade-in space-y-6">
        {/* Welcome */}
        <div className="page-header">
          <h1 className="page-title">{greeting}, {firstName}.</h1>
          <p className="page-subtitle">How can we help you today?</p>
        </div>

        {/* Quick actions */}
        <div className="grid sm:grid-cols-3 gap-4">
          {[
            { label: 'Find a Doctor',      icon: Search,       to: '/patient/browse',       cls: 'bg-navy-700 text-white', iconCls: 'text-navy-200' },
            { label: 'My Appointments',    icon: Calendar,     to: '/patient/appointments', cls: 'bg-white border border-slate-200', iconCls: 'text-navy-600' },
            { label: 'Browse Specialties', icon: Clock,        to: '/providers',            cls: 'bg-white border border-slate-200', iconCls: 'text-navy-600' },
          ].map(a => (
            <Link key={a.label} to={a.to}
              className={`${a.cls} rounded-xl p-5 flex items-center justify-between group hover:shadow-card-hover transition-all duration-200`}>
              <span className={`font-medium text-sm ${a.cls.includes('navy-700') ? 'text-white' : 'text-slate-700'}`}>{a.label}</span>
              <a.icon className={`h-5 w-5 ${a.iconCls}`} />
            </Link>
          ))}
        </div>

        {/* Featured providers */}
        {topProviders.length > 0 && (
          <div className="card">
            <div className="flex items-center justify-between mb-5">
              <h2 className="font-serif text-lg text-navy-900">Featured Doctors</h2>
              <Link to="/patient/browse" className="text-sm text-navy-600 hover:underline font-medium flex items-center gap-1">
                View all <ArrowRight className="h-3.5 w-3.5" />
              </Link>
            </div>
            <div className="divide-y divide-slate-100">
              {topProviders.map(p => (
                <Link key={p.providerId} to={`/providers/${p.providerId}`}
                  className="flex items-center gap-4 py-3.5 first:pt-0 last:pb-0 hover:bg-slate-50 -mx-2 px-2 rounded-lg transition-colors">
                  <div className="h-10 w-10 rounded-xl bg-gradient-to-br from-navy-700 to-navy-500 flex items-center justify-center text-white text-sm font-serif flex-shrink-0 overflow-hidden">
                    {p.profilePicUrl ? <img src={p.profilePicUrl} alt="" className="h-full w-full object-cover" /> : (p.clinicName?.slice(0,2) || 'DR')}
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-slate-800 truncate">{p.clinicName || 'Medical Clinic'}</p>
                    <p className="text-xs text-emerald-600">{p.specialization}</p>
                  </div>
                  <div className="text-right flex-shrink-0">
                    {p.consultationFee > 0 && <p className="text-sm font-semibold text-navy-700">₹{p.consultationFee}</p>}
                    <p className={`text-xs font-medium ${p.isAvailable ? 'text-emerald-600' : 'text-slate-400'}`}>
                      {p.isAvailable ? 'Available' : 'On leave'}
                    </p>
                  </div>
                </Link>
              ))}
            </div>
          </div>
        )}

        {/* Profile card */}
        <div className="card">
          <h2 className="font-serif text-lg text-navy-900 mb-4">My Profile</h2>
          <div className="flex items-center gap-4">
            <div className="h-12 w-12 rounded-full bg-navy-100 flex items-center justify-center overflow-hidden">
              {user?.profilePicUrl
                ? <img src={user.profilePicUrl} alt="" className="h-full w-full object-cover" />
                : <User className="h-6 w-6 text-navy-500" />
              }
            </div>
            <div>
              <p className="font-medium text-slate-900">{user?.fullName}</p>
              <p className="text-sm text-slate-500">{user?.email}</p>
              {user?.phone && <p className="text-xs text-slate-400">{user.phone}</p>}
            </div>
          </div>
        </div>
      </div>
    </DashboardLayout>
  )
}

export default function PatientDashboard() {
  return <ToastProvider><PatientDashboardInner /></ToastProvider>
}

// src/app/features/patient/patient-dashboard.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { SidebarLayoutComponent, NavItem } from '../../shared/components/sidebar-layout.component';
import { AuthService } from '../../core/services/auth.service';
import { AppointmentService } from '../../core/services/appointment.service';
import { AppointmentSummary } from '../../core/models';
import { StatusBadgePipe, FormatTimePipe, FormatDatePipe } from '../../shared/pipes/status.pipe';

@Component({
  selector: 'app-patient-dashboard',
  standalone: true,
  imports: [CommonModule, RouterModule, SidebarLayoutComponent, StatusBadgePipe, FormatTimePipe, FormatDatePipe],
  template: `
    <app-sidebar-layout [navItems]="navItems">
      <div class="page-enter">
        <!-- Header -->
        <div class="mb-8">
          <h1 class="text-3xl font-serif text-navy-700">Good {{ greeting }}, {{ firstName }}!</h1>
          <p class="text-gray-500 mt-1">Here's your health overview</p>
        </div>

        <!-- Stats -->
        <div class="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
          @for (stat of stats; track stat.label) {
            <div class="card">
              <div class="text-2xl mb-1">{{ stat.icon }}</div>
              <p class="text-2xl font-bold text-navy-700">{{ stat.value }}</p>
              <p class="text-gray-500 text-xs mt-0.5">{{ stat.label }}</p>
            </div>
          }
        </div>

        <!-- Upcoming appointments -->
        <div class="card">
          <div class="flex items-center justify-between mb-5">
            <h2 class="text-xl font-serif text-navy-700">Upcoming Appointments</h2>
            <a routerLink="/patient/appointments" class="text-sm text-emerald-600 font-medium hover:underline">View all</a>
          </div>

          @if (loading) {
            <div class="space-y-3">
              @for (i of [1,2,3]; track i) {
                <div class="animate-pulse h-16 bg-gray-100 rounded-xl"></div>
              }
            </div>
          }

          @if (!loading && upcoming.length === 0) {
            <div class="text-center py-8 text-gray-400">
              <div class="text-4xl mb-3">📅</div>
              <p>No upcoming appointments</p>
              <a routerLink="/patient/browse" class="btn-primary inline-block mt-4 text-sm py-2">Find a Doctor</a>
            </div>
          }

          @if (!loading) {
            <div class="divide-y divide-gray-100">
              @for (appt of upcoming.slice(0, 5); track appt.appointmentId) {
                <div class="py-4 flex items-center justify-between">
                  <div>
                    <p class="font-medium text-gray-900">{{ appt.serviceType }}</p>
                    <p class="text-sm text-gray-500">{{ appt.appointmentDate | formatDate }} · {{ appt.startTime | formatTime }}</p>
                    <p class="text-xs text-gray-400 mt-0.5">{{ appt.modeOfConsultation === 'VIDEO' ? '📹 Video' : '🏥 In-Person' }}</p>
                  </div>
                  <span [ngClass]="appt.status | statusBadge">{{ appt.status }}</span>
                </div>
              }
            </div>
          }
        </div>
      </div>
    </app-sidebar-layout>
  `
})
export class PatientDashboardComponent implements OnInit {
  private auth = inject(AuthService);
  private appointmentService = inject(AppointmentService);

  navItems: NavItem[] = [
    { label: 'Dashboard', iconName: 'home', route: '/patient/dashboard' },
    { label: 'Find Doctors', iconName: 'search', route: '/patient/browse' },
    { label: 'My Appointments', iconName: 'calendar', route: '/patient/appointments' },
    { label: 'Profile', iconName: 'user', route: '/patient/profile' },
  ];

  upcoming: AppointmentSummary[] = [];
  loading = true;

  get greeting(): string {
    const h = new Date().getHours();
    return h < 12 ? 'morning' : h < 17 ? 'afternoon' : 'evening';
  }

  get firstName(): string {
    return this.auth.currentUser()?.fullName.split(' ')[0] || 'there';
  }

  get stats() {
    return [
      { icon: '📅', value: this.upcoming.length, label: 'Upcoming' },
      { icon: '✅', value: '–', label: 'Completed' },
      { icon: '❌', value: '–', label: 'Cancelled' },
      { icon: '🏥', value: '–', label: 'Total Visits' },
    ];
  }

  ngOnInit(): void {
    const userId = this.auth.currentUser()?.userId!;
    this.appointmentService.getPatientUpcoming(userId).subscribe({
      next: (a) => { this.upcoming = a; this.loading = false; },
      error: () => { this.loading = false; }
    });
  }
}
