// src/app/shared/components/confirm-modal.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-confirm-modal',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    @if (open) {
      <div class="fixed inset-0 z-50 flex items-center justify-center p-4">
        <div class="absolute inset-0 bg-black/50 backdrop-blur-sm" (click)="onCancel()"></div>
        <div class="relative bg-white rounded-2xl shadow-2xl max-w-md w-full p-6 page-enter">
          <div class="flex items-center gap-3 mb-4">
            <div class="w-10 h-10 rounded-full flex items-center justify-center text-xl"
              [ngClass]="danger ? 'bg-red-100' : 'bg-amber-100'">
              {{ danger ? '🗑️' : '⚠️' }}
            </div>
            <h3 class="text-lg font-semibold text-gray-900">{{ title }}</h3>
          </div>
          <p class="text-gray-600 mb-4">{{ message }}</p>

          @if (requireReason) {
            <div class="mb-4">
              <label class="block text-sm font-medium text-gray-700 mb-1">{{ reasonLabel }}</label>
              <textarea [(ngModel)]="reason" rows="3" class="input-field resize-none"
                [placeholder]="reasonPlaceholder"></textarea>
            </div>
          }

          <div class="flex gap-3 justify-end">
            <button class="btn-secondary" (click)="onCancel()">{{ cancelText }}</button>
            <button
              class="px-5 py-2.5 rounded-lg font-medium text-white transition-colors duration-200"
              [ngClass]="danger ? 'bg-red-600 hover:bg-red-700' : 'bg-navy-700 hover:bg-navy-800'"
              [disabled]="requireReason && !reason.trim()"
              (click)="onConfirm()">
              {{ confirmText }}
            </button>
          </div>
        </div>
      </div>
    }
  `
})
export class ConfirmModalComponent {
  @Input() open = false;
  @Input() title = 'Confirm Action';
  @Input() message = 'Are you sure?';
  @Input() confirmText = 'Confirm';
  @Input() cancelText = 'Cancel';
  @Input() danger = false;
  @Input() requireReason = false;
  @Input() reasonLabel = 'Reason';
  @Input() reasonPlaceholder = 'Enter reason...';
  @Output() confirmed = new EventEmitter<string>();
  @Output() cancelled = new EventEmitter<void>();

  reason = '';

  onConfirm(): void {
    this.confirmed.emit(this.reason);
    this.reason = '';
  }

  onCancel(): void {
    this.cancelled.emit();
    this.reason = '';
  }
}

// src/components/common/ConfirmModal.jsx
import React from 'react'
import { AlertTriangle } from 'lucide-react'

export default function ConfirmModal({ isOpen, title, message, onConfirm, onCancel, confirmLabel = 'Confirm', confirmClass = 'btn-danger', loading }) {
  if (!isOpen) return null
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-navy-950/40 backdrop-blur-sm" onClick={onCancel} />
      <div className="relative bg-white rounded-2xl shadow-card-hover max-w-md w-full p-6 animate-slide-up">
        <div className="flex items-start gap-4">
          <div className="h-10 w-10 rounded-full bg-red-100 flex items-center justify-center flex-shrink-0">
            <AlertTriangle className="h-5 w-5 text-red-600" />
          </div>
          <div className="flex-1">
            <h3 className="font-serif text-lg text-slate-900 mb-1">{title}</h3>
            <p className="text-sm text-slate-500">{message}</p>
          </div>
        </div>
        <div className="flex gap-3 mt-6 justify-end">
          <button onClick={onCancel} className="btn-secondary" disabled={loading}>Cancel</button>
          <button onClick={onConfirm} className={confirmClass} disabled={loading}>
            {loading ? 'Processing…' : confirmLabel}
          </button>
        </div>
      </div>
    </div>
  )
}
