// src/app/features/auth/provider-directory.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, ActivatedRoute } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { NavbarComponent } from '../../shared/components/navbar.component';
import { ProviderService } from '../../core/services/provider.service';
import { ProviderSummary } from '../../core/models';

@Component({
  selector: 'app-provider-directory',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule, NavbarComponent],
  template: `
    <app-navbar></app-navbar>

    <div class="bg-navy-700 py-12 px-4">
      <div class="max-w-4xl mx-auto">
        <h1 class="text-4xl font-serif text-white mb-6 text-center">Find Your Doctor</h1>
        <div class="flex gap-3">
          <input type="text" [(ngModel)]="searchQuery" (input)="onSearch()" placeholder="Search by name or specialization…"
            class="flex-1 input-field text-base py-3">
          <button (click)="onSearch()" class="btn-emerald px-6">Search</button>
        </div>
      </div>
    </div>

    <div class="max-w-7xl mx-auto px-4 py-8">
      <!-- Filters -->
      <div class="flex flex-wrap gap-2 mb-6">
        <button (click)="filterSpec('')" class="px-4 py-1.5 rounded-full text-sm font-medium transition-all border"
          [ngClass]="activeSpec === '' ? 'bg-navy-700 text-white border-navy-700' : 'bg-white text-gray-600 border-gray-200 hover:border-navy-300'">
          All
        </button>
        @for (spec of specializations; track spec) {
          <button (click)="filterSpec(spec)" class="px-4 py-1.5 rounded-full text-sm font-medium transition-all border"
            [ngClass]="activeSpec === spec ? 'bg-navy-700 text-white border-navy-700' : 'bg-white text-gray-600 border-gray-200 hover:border-navy-300'">
            {{ spec }}
          </button>
        }
      </div>

      <!-- Loading -->
      @if (loading) {
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          @for (i of [1,2,3,4,5,6]; track i) {
            <div class="card animate-pulse">
              <div class="flex gap-4">
                <div class="w-16 h-16 bg-gray-200 rounded-full"></div>
                <div class="flex-1">
                  <div class="h-4 bg-gray-200 rounded mb-2"></div>
                  <div class="h-3 bg-gray-100 rounded w-2/3"></div>
                </div>
              </div>
            </div>
          }
        </div>
      }

      <!-- Results -->
      @if (!loading && providers.length === 0) {
        <div class="text-center py-16 text-gray-400">
          <div class="text-5xl mb-4">🔍</div>
          <p class="text-lg">No providers found. Try a different search.</p>
        </div>
      }

      @if (!loading) {
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          @for (provider of providers; track provider.providerId) {
            <div class="card hover:shadow-md transition-shadow group">
              <div class="flex items-start gap-4 mb-4">
                <div class="w-14 h-14 rounded-full bg-navy-100 flex items-center justify-center text-navy-700 font-bold text-lg flex-shrink-0 overflow-hidden">
                  @if (provider.profilePicUrl) {
                    <img [src]="provider.profilePicUrl" class="w-full h-full object-cover" alt="">
                  } @else {
                    {{ (provider.fullName || provider.clinicName || '?')[0].toUpperCase() }}
                  }
                </div>
                <div class="flex-1 min-w-0">
                  <h3 class="font-semibold text-gray-900 truncate">{{ provider.fullName || 'Dr. ' + provider.clinicName }}</h3>
                  <p class="text-emerald-600 text-sm font-medium">{{ provider.specialization }}</p>
                  @if (provider.experienceYears) {
                    <p class="text-gray-400 text-xs">{{ provider.experienceYears }} yrs experience</p>
                  }
                </div>
              </div>

              @if (provider.clinicName) {
                <p class="text-gray-500 text-sm mb-1">🏥 {{ provider.clinicName }}</p>
              }
              @if (provider.clinicAddress) {
                <p class="text-gray-400 text-xs mb-3">📍 {{ provider.clinicAddress }}</p>
              }

              <div class="flex items-center justify-between pt-3 border-t border-gray-100">
                <div class="flex items-center gap-3 text-sm">
                  @if (provider.consultationFee) {
                    <span class="text-navy-700 font-semibold">₹{{ provider.consultationFee }}</span>
                  }
                  @if (provider.avgRating) {
                    <span class="text-amber-500">★ {{ provider.avgRating.toFixed(1) }}</span>
                  }
                  <span class="text-xs px-2 py-0.5 rounded-full"
                    [ngClass]="provider.isAvailable ? 'bg-emerald-100 text-emerald-700' : 'bg-gray-100 text-gray-500'">
                    {{ provider.isAvailable ? 'Available' : 'Busy' }}
                  </span>
                </div>
                <a [routerLink]="['/providers', provider.providerId]"
                  class="text-sm text-navy-700 font-medium hover:underline group-hover:text-emerald-600 transition-colors">
                  Book →
                </a>
              </div>
            </div>
          }
        </div>
      }
    </div>
  `
})
export class ProviderDirectoryComponent implements OnInit {
  private providerService = inject(ProviderService);
  private route = inject(ActivatedRoute);

  providers: ProviderSummary[] = [];
  loading = true;
  searchQuery = '';
  activeSpec = '';
  specializations = ['Cardiology', 'Neurology', 'Dentistry', 'Ophthalmology', 'Orthopedics', 'Pediatrics', 'General Medicine', 'Dermatology', 'Psychiatry', 'Gynecology'];

  ngOnInit(): void {
    const spec = this.route.snapshot.queryParamMap.get('spec');
    if (spec) { this.activeSpec = spec; this.filterSpec(spec); }
    else this.loadAll();
  }

  loadAll(): void {
    this.loading = true;
    this.providerService.getAll().subscribe({
      next: (p) => { this.providers = p; this.loading = false; },
      error: () => { this.loading = false; }
    });
  }

  onSearch(): void {
    if (!this.searchQuery.trim()) { this.loadAll(); return; }
    this.loading = true;
    this.providerService.search(this.searchQuery).subscribe({
      next: (p) => { this.providers = p; this.loading = false; },
      error: () => { this.loading = false; }
    });
  }

  filterSpec(spec: string): void {
    this.activeSpec = spec;
    if (!spec) { this.loadAll(); return; }
    this.loading = true;
    this.providerService.bySpecialization(spec).subscribe({
      next: (p) => { this.providers = p; this.loading = false; },
      error: () => { this.loading = false; }
    });
  }
}

// src/pages/public/ProviderDirectory.jsx
import React, { useState, useEffect, useCallback } from 'react'
import { useSearchParams } from 'react-router-dom'
import PublicNav from '../../components/layout/PublicNav'
import ProviderCard from '../../components/common/ProviderCard'
import { ToastProvider } from '../../components/common/Toast'
import { EmptyState } from '../../components/common/Feedback'
import Spinner from '../../components/common/Spinner'
import { getVerifiedProviders, searchProviders, getBySpecialization } from '../../api/providerService'
import { Search, Filter, X, Users } from 'lucide-react'

const SPECS = [
  'All', 'Cardiology', 'Dermatology', 'Orthopedics', 'Neurology',
  'Pediatrics', 'Ophthalmology', 'ENT', 'General Medicine', 'Psychiatry', 'Gynecology'
]

function ProviderDirectoryInner() {
  const [searchParams, setSearchParams] = useSearchParams()
  const [providers, setProviders] = useState([])
  const [loading, setLoading]     = useState(true)
  const [query, setQuery]         = useState(searchParams.get('q') || '')
  const [activeSpec, setActiveSpec] = useState(searchParams.get('spec') || 'All')
  const [availOnly, setAvailOnly] = useState(false)

  const load = useCallback(async () => {
    setLoading(true)
    try {
      let data
      if (query.trim()) {
        const res = await searchProviders(query.trim())
        data = res.data
      } else if (activeSpec && activeSpec !== 'All') {
        const res = await getBySpecialization(activeSpec)
        data = res.data
      } else {
        const res = await getVerifiedProviders()
        data = res.data
      }
      setProviders(availOnly ? data.filter(p => p.isAvailable) : data)
    } catch {
      setProviders([])
    } finally {
      setLoading(false)
    }
  }, [query, activeSpec, availOnly])

  useEffect(() => { load() }, [load])

  const handleSearch = (e) => {
    e.preventDefault()
    setActiveSpec('All')
  }

  const handleSpecClick = (spec) => {
    setActiveSpec(spec)
    setQuery('')
    setSearchParams(spec !== 'All' ? { spec } : {})
  }

  const clearFilters = () => {
    setQuery('')
    setActiveSpec('All')
    setAvailOnly(false)
    setSearchParams({})
  }

  const hasFilters = query || activeSpec !== 'All' || availOnly

  return (
    <div className="min-h-screen bg-slate-50">
      <PublicNav />

      {/* Header */}
      <div className="bg-white border-b border-slate-100">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-8">
          <h1 className="font-serif text-3xl text-navy-900 mb-1">Find a Doctor</h1>
          <p className="text-slate-500 text-sm mb-6">Browse {providers.length} verified healthcare providers</p>

          {/* Search */}
          <form onSubmit={handleSearch} className="flex gap-3 max-w-xl">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
              <input
                type="text"
                value={query}
                onChange={e => setQuery(e.target.value)}
                placeholder="Search by name, specialization, clinic…"
                className="input-field pl-9"
              />
            </div>
            <button type="submit" className="btn-primary px-5">Search</button>
          </form>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 py-6">
        {/* Filters row */}
        <div className="flex flex-col sm:flex-row gap-3 items-start sm:items-center mb-6">
          {/* Spec pills — scrollable */}
          <div className="flex gap-2 overflow-x-auto pb-1 flex-1 scrollbar-hide">
            {SPECS.map(s => (
              <button
                key={s}
                onClick={() => handleSpecClick(s)}
                className={`flex-shrink-0 px-3.5 py-1.5 rounded-full text-xs font-medium transition-all duration-150 ${
                  activeSpec === s
                    ? 'bg-navy-700 text-white'
                    : 'bg-white border border-slate-200 text-slate-600 hover:border-navy-300 hover:text-navy-600'
                }`}
              >
                {s}
              </button>
            ))}
          </div>
          {/* Available toggle */}
          <label className="flex items-center gap-2 flex-shrink-0 cursor-pointer">
            <div
              onClick={() => setAvailOnly(!availOnly)}
              className={`relative w-9 h-5 rounded-full transition-colors ${availOnly ? 'bg-emerald-500' : 'bg-slate-200'}`}
            >
              <div className={`absolute top-0.5 left-0.5 h-4 w-4 rounded-full bg-white shadow transition-transform ${availOnly ? 'translate-x-4' : ''}`} />
            </div>
            <span className="text-xs font-medium text-slate-600">Available only</span>
          </label>
          {hasFilters && (
            <button onClick={clearFilters} className="flex-shrink-0 flex items-center gap-1 text-xs text-slate-500 hover:text-red-500 transition-colors">
              <X className="h-3.5 w-3.5" /> Clear
            </button>
          )}
        </div>

        {/* Results */}
        {loading ? (
          <div className="flex justify-center py-20"><Spinner size="lg" /></div>
        ) : providers.length === 0 ? (
          <EmptyState
            icon={Users}
            title="No providers found"
            description="Try adjusting your search or filters."
            action={hasFilters && <button onClick={clearFilters} className="btn-secondary text-sm">Clear filters</button>}
          />
        ) : (
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
            {providers.map(p => (
              <ProviderCard key={p.providerId} provider={p} />
            ))}
          </div>
        )}
      </div>
    </div>
  )
}

export default function ProviderDirectory() {
  return <ToastProvider><ProviderDirectoryInner /></ToastProvider>
}
