// src/app/features/admin/admin-dashboard.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { SidebarLayoutComponent, NavItem } from '../../shared/components/sidebar-layout.component';
import { ProviderService } from '../../core/services/provider.service';
import { AppointmentService } from '../../core/services/appointment.service';
import { ProviderResponse, SpecializationCount } from '../../core/models';
import { StatusBadgePipe } from '../../shared/pipes/status.pipe';

@Component({
  selector: 'app-admin-dashboard',
  standalone: true,
  imports: [CommonModule, RouterModule, SidebarLayoutComponent, StatusBadgePipe],
  template: `
    <app-sidebar-layout [navItems]="navItems">
      <div class="page-enter">
        <div class="mb-8">
          <h1 class="text-3xl font-serif text-navy-700">Admin Dashboard</h1>
          <p class="text-gray-500 mt-1">Platform overview</p>
        </div>

        <!-- Stats -->
        <div class="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
          <div class="card">
            <div class="text-2xl mb-1">👨‍⚕️</div>
            <p class="text-2xl font-bold text-navy-700">{{ totalProviders }}</p>
            <p class="text-gray-500 text-xs mt-0.5">Total Providers</p>
          </div>
          <div class="card">
            <div class="text-2xl mb-1">⏳</div>
            <p class="text-2xl font-bold text-amber-600">{{ pendingProviders.length }}</p>
            <p class="text-gray-500 text-xs mt-0.5">Pending Approval</p>
          </div>
          <div class="card">
            <div class="text-2xl mb-1">✅</div>
            <p class="text-2xl font-bold text-emerald-600">{{ approvedCount }}</p>
            <p class="text-gray-500 text-xs mt-0.5">Approved</p>
          </div>
          <div class="card">
            <div class="text-2xl mb-1">📊</div>
            <p class="text-2xl font-bold text-navy-700">{{ specializations.length }}</p>
            <p class="text-gray-500 text-xs mt-0.5">Specializations</p>
          </div>
        </div>

        <div class="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
          <!-- Pending queue -->
          <div class="card">
            <div class="flex items-center justify-between mb-4">
              <h2 class="text-xl font-serif text-navy-700">Pending Approvals</h2>
              <a routerLink="/admin/pending" class="text-sm text-emerald-600 hover:underline">View all</a>
            </div>
            @if (pendingLoading) {
              <div class="space-y-2">
                @for (i of [1,2,3]; track i) { <div class="h-12 bg-gray-100 rounded-lg animate-pulse"></div> }
              </div>
            }
            @if (!pendingLoading && pendingProviders.length === 0) {
              <div class="text-center py-8 text-gray-400">
                <div class="text-3xl mb-2">🎉</div>
                <p>No pending approvals!</p>
              </div>
            }
            @if (!pendingLoading) {
              <div class="divide-y divide-gray-100">
                @for (p of pendingProviders.slice(0, 5); track p.providerId) {
                  <div class="py-3 flex items-center justify-between">
                    <div>
                      <p class="font-medium text-gray-900 text-sm">{{ p.specialization }}</p>
                      <p class="text-xs text-gray-400">{{ p.qualification }} · {{ p.experienceYears }}yrs</p>
                    </div>
                    <a [routerLink]="['/admin/providers', p.providerId]" class="text-xs text-navy-700 hover:underline">Review →</a>
                  </div>
                }
              </div>
            }
          </div>

          <!-- Specialization chart -->
          <div class="card">
            <h2 class="text-xl font-serif text-navy-700 mb-4">Specializations</h2>
            @if (specLoading) {
              <div class="space-y-2">
                @for (i of [1,2,3,4]; track i) { <div class="h-8 bg-gray-100 rounded animate-pulse"></div> }
              </div>
            }
            @if (!specLoading) {
              <div class="space-y-3">
                @for (spec of specializations.slice(0, 8); track spec.specialization) {
                  <div>
                    <div class="flex justify-between text-sm mb-1">
                      <span class="text-gray-700">{{ spec.specialization }}</span>
                      <span class="text-gray-500 font-medium">{{ spec.count }}</span>
                    </div>
                    <div class="h-2 bg-gray-100 rounded-full overflow-hidden">
                      <div class="h-full bg-navy-600 rounded-full transition-all duration-700"
                        [style.width.%]="maxSpecCount ? (spec.count / maxSpecCount) * 100 : 0">
                      </div>
                    </div>
                  </div>
                }
              </div>
            }
          </div>
        </div>
      </div>
    </app-sidebar-layout>
  `
})
export class AdminDashboardComponent implements OnInit {
  private providerService = inject(ProviderService);

  navItems: NavItem[] = [
    { label: 'Dashboard', icon: '🏠', route: '/admin/dashboard' },
    { label: 'Pending Approvals', icon: '⏳', route: '/admin/pending' },
    { label: 'All Providers', icon: '👨‍⚕️', route: '/admin/providers' },
  ];

  pendingProviders: ProviderResponse[] = [];
  pendingLoading = true;
  totalProviders = 0;
  approvedCount = 0;
  specializations: SpecializationCount[] = [];
  specLoading = true;

  get maxSpecCount(): number {
    return Math.max(...this.specializations.map(s => s.count), 1);
  }

  ngOnInit(): void {
    this.providerService.adminGetPending().subscribe({
      next: (p) => { this.pendingProviders = p; this.pendingLoading = false; },
      error: () => { this.pendingLoading = false; }
    });

    this.providerService.adminGetAll().subscribe({
      next: (all) => {
        this.totalProviders = all.length;
        this.approvedCount = all.filter(p => p.verificationStatus === 'APPROVED').length;
      }
    });

    this.providerService.getSpecializationAnalytics().subscribe({
      next: (s) => {
        this.specializations = s.sort((a, b) => b.count - a.count);
        this.specLoading = false;
      },
      error: () => { this.specLoading = false; }
    });
  }
}

// src/pages/admin/AdminDashboard.jsx
import React, { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import DashboardLayout from '../../components/layout/DashboardLayout'
import { ToastProvider } from '../../components/common/Toast'
import Spinner from '../../components/common/Spinner'
import { adminGetAllProviders, adminGetPendingProviders, getSpecializationStats } from '../../api/providerService'
import { getAdminUsers } from '../../api/authService'
import { Users, UserCheck, Clock, BarChart3, ArrowRight, CheckCircle, XCircle, AlertCircle } from 'lucide-react'

function StatCard({ label, value, icon: Icon, sub, color = 'navy' }) {
  const colors = {
    navy:    'bg-navy-700 text-white',
    emerald: 'bg-emerald-500 text-white',
    amber:   'bg-amber-500 text-white',
    red:     'bg-red-500 text-white',
  }
  return (
    <div className="card flex items-start gap-4">
      <div className={`h-11 w-11 rounded-xl flex items-center justify-center flex-shrink-0 ${colors[color]}`}>
        <Icon className="h-5 w-5" />
      </div>
      <div>
        <p className="section-label">{label}</p>
        <p className="font-serif text-3xl text-navy-900 leading-none mt-1">{value ?? '—'}</p>
        {sub && <p className="text-xs text-slate-400 mt-1">{sub}</p>}
      </div>
    </div>
  )
}

function AdminDashboardInner() {
  const [allProviders, setAllProviders]     = useState([])
  const [pendingProviders, setPendingProviders] = useState([])
  const [specs, setSpecs]                   = useState([])
  const [loading, setLoading]               = useState(true)

  useEffect(() => {
    Promise.allSettled([
      adminGetAllProviders(),
      adminGetPendingProviders(),
      getSpecializationStats(),
    ]).then(([all, pending, specRes]) => {
      if (all.status === 'fulfilled')     setAllProviders(all.value.data)
      if (pending.status === 'fulfilled') setPendingProviders(pending.value.data)
      if (specRes.status === 'fulfilled') setSpecs(specRes.value.data)
    }).finally(() => setLoading(false))
  }, [])

  const approved  = allProviders.filter(p => p.verificationStatus === 'APPROVED')
  const rejected  = allProviders.filter(p => p.verificationStatus === 'REJECTED')
  const available = approved.filter(p => p.isAvailable)

  const maxCount = specs.length ? Math.max(...specs.map(s => s.count)) : 1

  if (loading) return <DashboardLayout><div className="flex justify-center py-20"><Spinner size="lg" /></div></DashboardLayout>

  return (
    <DashboardLayout>
      <div className="animate-fade-in space-y-6">
        <div className="page-header">
          <h1 className="page-title">Admin Dashboard</h1>
          <p className="page-subtitle">Platform overview and management</p>
        </div>

        {/* Stats grid */}
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <StatCard label="Total Providers"   value={allProviders.length}     icon={Users}      color="navy" />
          <StatCard label="Approved Doctors"  value={approved.length}         icon={CheckCircle} color="emerald" />
          <StatCard label="Pending Review"    value={pendingProviders.length} icon={Clock}       color="amber" sub={pendingProviders.length ? 'Needs attention' : 'All clear'} />
          <StatCard label="Available Now"     value={available.length}        icon={UserCheck}   color="navy" />
        </div>

        {/* Pending queue preview */}
        <div className="card">
          <div className="flex items-center justify-between mb-5">
            <h2 className="font-serif text-lg text-navy-900 flex items-center gap-2">
              <AlertCircle className="h-5 w-5 text-amber-500" />
              Pending Approvals
              {pendingProviders.length > 0 && (
                <span className="ml-1 h-5 w-5 rounded-full bg-amber-500 text-white text-xs flex items-center justify-center font-bold">
                  {pendingProviders.length}
                </span>
              )}
            </h2>
            <Link to="/admin/pending" className="text-sm text-navy-600 hover:underline font-medium flex items-center gap-1">
              View all <ArrowRight className="h-3.5 w-3.5" />
            </Link>
          </div>
          {pendingProviders.length === 0 ? (
            <div className="flex items-center gap-3 py-4 text-sm text-emerald-600">
              <CheckCircle className="h-5 w-5" />
              No pending approvals. All caught up!
            </div>
          ) : (
            <div className="divide-y divide-slate-100">
              {pendingProviders.slice(0, 5).map(p => (
                <Link key={p.providerId} to={`/admin/providers/${p.providerId}`}
                  className="flex items-center gap-4 py-3.5 first:pt-0 hover:bg-slate-50 -mx-2 px-2 rounded-lg transition-colors">
                  <div className="h-9 w-9 rounded-xl bg-gradient-to-br from-navy-700 to-navy-500 flex items-center justify-center text-white text-xs font-serif overflow-hidden flex-shrink-0">
                    {p.profilePicUrl ? <img src={p.profilePicUrl} alt="" className="h-full w-full object-cover" /> : p.clinicName?.slice(0,2) || 'DR'}
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-slate-800 truncate">{p.clinicName || 'Medical Clinic'}</p>
                    <p className="text-xs text-slate-400">{p.specialization} · {p.experienceYears}y exp</p>
                  </div>
                  <span className="badge-pending flex-shrink-0">Pending</span>
                </Link>
              ))}
            </div>
          )}
        </div>

        {/* Specialization bar chart */}
        {specs.length > 0 && (
          <div className="card">
            <h2 className="font-serif text-lg text-navy-900 mb-5 flex items-center gap-2">
              <BarChart3 className="h-5 w-5 text-navy-500" />
              Providers by Specialization
            </h2>
            <div className="space-y-3">
              {[...specs].sort((a,b) => b.count - a.count).slice(0, 10).map(s => (
                <div key={s.specialization} className="flex items-center gap-3">
                  <span className="text-xs text-slate-500 w-32 flex-shrink-0 truncate">{s.specialization}</span>
                  <div className="flex-1 bg-slate-100 rounded-full h-2.5 overflow-hidden">
                    <div
                      className="h-full bg-navy-600 rounded-full transition-all duration-500"
                      style={{ width: `${(s.count / maxCount) * 100}%` }}
                    />
                  </div>
                  <span className="text-xs font-semibold text-navy-700 w-6 text-right flex-shrink-0">{s.count}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Status breakdown */}
        <div className="card">
          <h2 className="font-serif text-lg text-navy-900 mb-5">Provider Status Breakdown</h2>
          <div className="grid sm:grid-cols-3 gap-4">
            {[
              { label: 'Approved', count: approved.length,            cls: 'text-emerald-600', bar: 'bg-emerald-500' },
              { label: 'Pending',  count: pendingProviders.length,    cls: 'text-amber-600',   bar: 'bg-amber-500' },
              { label: 'Rejected', count: rejected.length,            cls: 'text-red-600',     bar: 'bg-red-500' },
            ].map(item => (
              <div key={item.label} className="text-center p-4 rounded-xl bg-slate-50 border border-slate-100">
                <p className={`font-serif text-3xl ${item.cls}`}>{item.count}</p>
                <p className="text-xs text-slate-500 mt-1 font-medium">{item.label}</p>
                <div className="mt-2 h-1.5 bg-slate-200 rounded-full overflow-hidden">
                  <div className={`h-full ${item.bar} rounded-full`}
                    style={{ width: allProviders.length ? `${(item.count / allProviders.length) * 100}%` : '0%' }} />
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </DashboardLayout>
  )
}

export default function AdminDashboard() {
  return <ToastProvider><AdminDashboardInner /></ToastProvider>
}
